name: "Steve O'Reilly DOP"
favicon: null
layout_spectrum: 1
typography_spectrum: 0.01609
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5
  lightness: 0.03714331821538508
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
